README.md, deploy/csi-driver-PSP.yaml, deploy/csi-driver.yaml
K8S v1.16 has few changes to the resources that require update to the deployment files.
* Expand CSI volume is promoted to Beta i.e; feature gate is enabled by default.
* Removed support for some of the old resource definition i.e; requires resource file updates
=> Update deployment files for K8S v1.16

Dockerfile, README.md, deploy/csi-driver-PSP.yaml, deploy/csi-driver.yaml, driver/driver.go, driver/mounter.go
When unmount fails, K8S not cleaning up the mount points
associated with the pod leading to orphaned pods and
log flooding. This patch fixes the issue by logging the
unmount failure in the driver and returning success to
the K8S (hence K8S cleansup properly).
The unmount failure can happen for two reasons:
1) The quobyte client is killed/terminated before
all the application pods are drained.
2) The Quobyte client is crashed and not
available during the unmount requests.
=> Fix orphaned pod log flooding

log_collector
adds kubeclt version (thereby kuberentes server and client version) to the collected logs
=> Add kubectl version information to the logs

README.md, deploy/csi-driver-PSP.yaml, deploy/csi-driver.yaml, driver/controller.go, driver/driver.go, example/StorageClass.yaml, main.go
Driver should be deployed with
--use_k8s_namespace_as_tenant=true. Defaultly
this option is disabled and should be enabled
by user.
Tenant is not created by Quobyte CSI plugin
and must be present in the Quobyte Storgate
before being used.
If mapping is enabled, StorageClass.parameters.
quobyteTenant is ignored and PVC.namespace is
used as quobyteTenant.
=> Map K8S namespace to Quobyte Tenant

quobyte-csi-driver/templates/csi-driver.yaml
The yaml has indentation issue for the combination
enableSnapshots: true and podSecurityPolicies: true
https://github.com/quobyte/quobyte-csi/issues/22
=> PSP: Fix indentation for the PSP definitions

driver/node.go, example/volume-snapshot-class.yaml, example/volume-snapshot-content-pre-provisioned.yaml, example/volume-snapshot-dynamic-provision.yaml, example/volume-snapshot-pre-provisioned.yaml, quobyte-csi-driver/templates/csi-driver.yaml, quobyte-csi-driver/values.yaml
Fixes a mounting issue on k8s v1.20.x
Kubenetes no longer [creating whole path](https://github.com/quobyte/quobyte-csi/issues/28) inside /var/lib/pods/... (leaving off last two directories)
=> Fix mounting issue on k8s v1.20.x

quobyte-csi-driver/templates/csi-driver.yaml
This commit will fix missing selector for PSP.
Currently StatefulSet `quobyte-csi-controller-csi-quobyte-com` for PSP does not have required `selector` field, so we cannot apply PSP-enabled `quobyte-csi` without change.
```
$ helm template --set quobyte.podSecurityPolicies=true quobyte-csi-driver/ | kubectl apply -f - --dry-run=client
error: error validating "STDIN": error validating data: ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
I verified this PR fixed the issue as follows.
```
$ helm template --set quobyte.podSecurityPolicies=true quobyte-csi-driver/ | kubectl apply -f - --dry-run=client
```
=> Fix missing selector for PSP

quobyte-csi-driver/templates/csi-driver.yaml
This commit will remove unused namespace for ClusterRole which is cluster-scoped.
=> Remove unused namespace for ClusterRole

quobyte-csi-driver/templates/csi-driver.yaml
This commit will remove duplicate `imagePullPolicy` keys. Duplicate keys cause `unmarshal errors` in latest kustomize ( https://github.com/kubernetes-sigs/kustomize/issues/3480)
```
$ kustomize build base
2021/02/16 15:08:49 failed to decode ynode: yaml: unmarshal errors:
line 115: mapping key "imagePullPolicy" already defined at line 90
```
=> Remove duplicate imagePullPolicy for quobyte-csi-plugin

driver/node.go
Fixes: https://github.com/quobyte/quobyte-csi/issues/34
This commit enables the VolumeStats feature in Kubernetes.
=> Add GET_VOLUME_STATS capability to NodeGetCapabilities

quobyte-csi-driver/templates/csi-driver.yaml
Right now it's impossible to include tolerations to the pods. It's pretty standard in helm charts to allow such configuration.
=> Allow including tolerations in pod configuration

quobyte-csi-driver/templates/pods/containers/_sidecar_snapshotter_container.tpl, quobyte-csi-driver/tests/__snapshot__/csi_driver_test.yaml.snap
This commit adds missing --csi-address flag for csi-snapshotter.
I found that csi-snapshotter cannot connect the CSI endpoint when enabling snapshots in helm value. (`enableSnapshots: true`)
```
W0119 06:23:43.531490       1 connection.go:172] Still connecting to unix:///run/csi/socket
W0119 06:23:53.531478       1 connection.go:172] Still connecting to unix:///run/csi/socket
```
`unix:///run/csi/socket` is the default value for csi endpoint, but quobyte-csi specifies `unix:///var/lib/csi/sockets/pluginproxy/csi.sock` for the endpoint.
https://github.com/quobyte/quobyte-csi/blob/v1.8.0/quobyte-csi-driver/templates/pods/containers/_quboyte_csi_controller_container.tpl#L27-L28
Other sidecars specify the path correctly like [this](https://github.com/quobyte/quobyte-csi/blob/v1.8.0/quobyte-csi …
=> Add --csi-address flag for csi-snapshotter

driver/controller.go, driver/driver.go, driver/node.go, driver/utils.go, example/StorageClass.yaml, go.mod, go.sum
* Quobyte API upgrade to v1.2.2
* Make Quobyte api credentials optional in node publish secrets
* Pre-provisioned volume PV should be configured with volume UUID to have optional api credentials
=> 1.8.1 release

docs/quobyte_access_keys.md, example/client.yaml
When access keys are used, quobyte client should be started with --enable-access-contexts and --no-default-permissions options. This patch updates the documentation and example client configuration to reflect these requirements.
=> Update configuration requirements for access keys

src/driver/controller.go, src/driver/utils.go
This PR adds missing error handling for volume expansion. It fixes the following potential bugs.
1. Because ControllerExpandVolume ignores errors, it might cause inconsistency between a PVC and a Quobyte Volume.
1. When the controller-expand-secret lacks keys, the quobyte-csi controller will panic.
=> Add missing error handling for volume expansion

docs/collect_quobyte_csi_logs.md
As log collector is a bash script, it was renamed
and added with extension. However, that change was not reflected in the documentation. So, update doc.
=> Reflect change of file extension in doc

csi-driver-templates/templates/pods/_quobyte_csi_pod_killer_cache.tpl, csi-driver-templates/tests/README.md, csi-driver-templates/tests/__snapshot__/csi_driver_test.yaml.snap, csi-driver-templates/values.yaml, kind-cluster/README.md, kind-cluster/run_test, src/Dockerfile
* Pod killer replicas can be configurable to support rolling upgrade scenarios
* Bumped pod killer to v0.2.1 that includes sticky cache critical fix
* Removed base image package caches to reduce the image size
* Improved kind test setup to pick pod killer automatically
=> Pod killer fixes

kind-cluster/e2e, src/driver/node.go, src/driver/utils.go, src/driver/utils_test.go, src/go.mod, src/go.sum
* Sets access keys on client mount instead of mountpoint/volume to accommodate untrusted clients
* Generates access key handle instead of using pod uid.
=> Accesskey fixes

csi-driver-templates/templates/pods/_quobyte_csi_controller_pod.tpl, csi-driver-templates/templates/pods/_quobyte_csi_node_driver_pod.tpl, csi-driver-templates/templates/pods/_quobyte_csi_pod_killer_cache.tpl, csi-driver-templates/values.yaml, kind-cluster/run_test
* Add node selector support to restrict Quobyte CSI Driver pod deployment to a subset of k8s cluster nodes
(Also, upgrades k8s test setup and related minor fixes)
=> Add node selector

csi-driver-templates/k8s-snapshot-controller.yaml, csi-driver-templates/k8s-snapshot-crd.yaml, csi-driver-templates/templates/pods/_quobyte_csi_controller_pod.tpl, csi-driver-templates/templates/pods/_quobyte_csi_node_driver_pod.tpl, csi-driver-templates/templates/pods/_quobyte_csi_pod_killer_cache.tpl, csi-driver-templates/templates/pods/containers/_quobyte_csi_controller_container.tpl, csi-driver-templates/templates/pods/rbac/_sidecar_snapshotter_rbac.tpl, csi-driver-templates/tests/__snapshot__/csi_driver_test.yaml.snap, csi-driver-templates/values.yaml, kind-cluster/README.md, kind-cluster/test-configs/local_cluster_3.x_shared_volume/values.yaml, src/cmd/main.go, src/driver/controller.go, src/driver/driver.go, src/driver/node_test.go, src/go.mod
* Cleanup shared volume with rm command option instead of delete files task
* Provide optional node labels for CSI Driver and pod killer cache
* Upgrade CSI sidecar containers
=> Cleanup shared volume with rm command
